version: "3.1"

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
      POSTGRES_DB: "pix"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  adminer:
    image: adminer
    ports:
      - 8090:8090
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge