version: "3.1"

services:

  mysqlsrv:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "pix"
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8082:8082
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge